// povray code generated by povexport.py

#include "colors.inc"
#include "stones.inc"
#include "woods.inc"
#include "metals.inc"

// Four-sided pyramid from shapes2.inc, slightly modified.
#declare Pyramid = union {
    triangle { <0, -1, -1>, <0, +1, -1>, <1, 0, 0> }
    triangle { <0, +1, -1>, <0, +1, +1>, <1, 0, 0> }
    triangle { <0, -1, +1>, <0, +1, +1>, <1, 0, 0> }
    triangle { <0, -1, +1>, <0, -1, -1>, <1, 0, 0> }
    triangle { <0, -1, -1>, <0, -1, +1>, <0, 1, 1> }
    triangle { <0, -1, -1>, <0, +1, -1>, <0, 1, 1> }
    scale <1, .5, .5>        // so height = width = 1
}
